spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: "jdbc:h2:mem:coupon_admin;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
file:
  upload-dir: /Users/psh/upload-folder
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  datasource:
    url: "jdbc:mysql://localhost/coupon_admin"
    username: "root"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
file:
  upload-dir: /Users/psh/upload-folder
logging:
  level:
    com.coupon.system: INFO
  file:
    path: /Users/psh/logs
    name: logs/coupon-admin.log